name:                delter
version:             0.1.0.0
github:              "githubuser/delter"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/delter#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- directory
- filepath
- fsnotify
- process
- temporary
- time
- unliftio

default-extensions:
- ImportQualifiedPost
- LambdaCase
- OverloadedStrings
- ScopedTypeVariables

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - Delter.FFI
  - Delter.Executable
  other-modules:
  - Delter.Types
  - Delter.FFI.C
  c-sources: cbits/xdelta3.c
  include-dirs: cbits
  install-includes: xdelta3.h
  cc-options: -std=c11 -DHAVE_CONFIG_H

executables:
  delter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - delter

  typst-test:
    main:                Main.hs
    source-dirs:         app/typst-test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - delter

  pandoc-test:
    main:                Main.hs
    source-dirs:         app/pandoc-test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - delter

tests:
  tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - delter
    - sandwich
    - text
    - QuickCheck
